"""create plan table

Revision ID: 76788ee0a450
Revises: 7e5842704703
Create Date: 2025-04-24 10:11:47.371139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76788ee0a450'
down_revision: Union[str, None] = '7e5842704703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('wakeup_time', sa.Time(), nullable=True),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('preferred_office_start_time', sa.Time(), nullable=True),
    sa.Column('preferred_office_end_time', sa.Time(), nullable=True),
    sa.Column('preferred_breakfast_time', sa.Time(), nullable=True),
    sa.Column('preferred_lunch_time', sa.Time(), nullable=True),
    sa.Column('preferred_dinner_time', sa.Time(), nullable=True),
    sa.Column('constraints_or_preference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('start', 'inprogress', 'completed', name='planstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    # ### end Alembic commands ###
