"""user adapt sso details

Revision ID: c551b217a699
Revises: 76788ee0a450
Create Date: 2025-04-26 10:06:34.383752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c551b217a699'
down_revision: Union[str, None] = '76788ee0a450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE authprovider AS ENUM ('google', 'microsoft')")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('output', sa.JSON(), nullable=True))
    op.add_column('plan', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('reflection', sa.Column('output', sa.JSON(), nullable=True))
    op.add_column('reflection', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('locale', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider', sa.Enum('GOOGLE', 'MICROSOFT', name='authprovider'), nullable=True))
    op.add_column('users', sa.Column('provider_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'picture')
    op.drop_column('reflection', 'updated_at')
    op.drop_column('reflection', 'output')
    op.drop_column('plan', 'updated_at')
    op.drop_column('plan', 'output')
    # ### end Alembic commands ###
    op.execute("DROP TYPE authprovider")
