"""add optional activity in plan

Revision ID: d62773d19e7e
Revises: c551b217a699
Create Date: 2025-04-27 21:28:15.397154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62773d19e7e'
down_revision: Union[str, None] = 'c551b217a699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('optional_activities', sa.JSON(), nullable=True))
    op.drop_column('plan', 'activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('activities', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('plan', 'optional_activities')
    # ### end Alembic commands ###
