"""create reflection

Revision ID: e0fb0844ba40
Revises: d5a591f5a4df
Create Date: 2025-04-24 00:06:23.684739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fb0844ba40'
down_revision: Union[str, None] = 'd5a591f5a4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('best_experience', sa.Text(), nullable=True),
    sa.Column('worst_experience', sa.Text(), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=True),
    sa.Column('happy_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('start', 'inprogress', 'completed', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflection')
    # ### end Alembic commands ###
